joint_mappings = {'lowerback_x': 0,
                  'lHip_1': 1,
                  'rHip_1': 2,
                  'lowerback_y': 3,
                  'lHip_2': 4,
                  'rHip_2': 5,
                  'lowerback_z': 6,
                  'lHip_torsion': 7,
                  'rHip_torsion': 8,
                  'upperback_x': 9,
                  'lKnee': 10,
                  'rKnee': 11,
                  'upperback_y': 12,
                  'lAnkle_1': 13,
                  'rAnkle_1': 14,
                  'upperback_z': 15,
                  'lAnkle_2': 16,
                  'rAnkle_2': 17,
                  'lowerneck_x': 18,
                  'lScapula_y': 19,
                  'rScapula_y': 20,
                  'lToeJoint': 21,
                  'rToeJoint': 22,
                  'lowerneck_y': 23,
                  'lScapula_z': 24,
                  'rScapula_z': 25,
                  'lowerneck_z': 26,
                  'lShoulder_1': 27,
                  'rShoulder_1': 28,
                  'upperneck_x': 29,
                  'lShoulder_2': 30,
                  'rShoulder_2': 31,
                  'upperneck_y': 32,
                  'lShoulder_torsion': 33,
                  'rShoulder_torsion': 34,
                  'upperneck_z': 35,
                  'lElbow_flexion_extension': 36,
                  'rElbow_flexion_extension': 37,
                  'lElbow_torsion': 38,
                  'rElbow_torsion': 39,
                  'lWrist_x': 40,
                  'rWrist_x': 41,
                  'lWrist_z': 42,
                  'rWrist_z': 43
                  }

rot_mappings = {'chest_rot': [joint_mappings['upperback_x'], 
                              joint_mappings['upperback_y'], 
                              joint_mappings['upperback_z']],
                'neck_rot': [joint_mappings['lowerneck_x'], 
                             joint_mappings['lowerneck_y'], 
                             joint_mappings['lowerneck_z']],
                'rhip_rot': [joint_mappings['rHip_1'], 
                             joint_mappings['rHip_2'], 
                             joint_mappings['rHip_torsion']],
                'rknee_rot': [joint_mappings['rKnee']],
                'rankle_rot': [joint_mappings['rAnkle_1'],
                               joint_mappings['rAnkle_2']],
                'rshoulder_rot': [joint_mappings['rShoulder_1'], 
                                  joint_mappings['rShoulder_2'], 
                                  joint_mappings['rShoulder_torsion']],
                'relbow_rot': [joint_mappings['rElbow_flexion_extension']],
                'lhip_rot': [joint_mappings['lHip_1'],
                             joint_mappings['lHip_2'],
                             joint_mappings['lHip_torsion']],
                'lknee_rot': [joint_mappings['lKnee']],
                'lankle_rot': [joint_mappings['lAnkle_1'],
                               joint_mappings['lAnkle_2']],
                'lshoulder_rot': [joint_mappings['lShoulder_1'],
                                  joint_mappings['lShoulder_2'],
                                  joint_mappings['lShoulder_torsion']],
                'lelbow_rot': [joint_mappings['lElbow_flexion_extension']]
}